CREATE DATABASE flow_tetyou
CREATE TABLE flow_tetyou.notes (
    id INT NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(255) NOT NULL,
    created_at DATE DEFAULT (CURRENT_DATE),
    text LONGTEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE flow_tetyou.users (
    id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);